# -*- coding: utf-8 -*-
"""tranformer-text generation-name entity recorg-quection/answering-summarization-while loop multiple questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7stmyYVnFerNHafkP9LrrzzEbTUMo1w
"""

!pip install transformers

from transformers import pipeline

analyser = pipeline('sentiment-analysis')

text_input = input('Enter some text: ')

result = analyser(text_input)

result

text_input = input('Enter some text: ')

result = analyser(text_input)

result

text_input = input('Enter some text: ')

result = analyser(text_input)

result

text_input = input('Enter some text: ')

result = analyser(text_input)

result

generage = pipeline('text-generation')

statement = input('Enter some text: ')

result = generage(statement,max_length=150)

result

entity_recog = pipeline('ner')

statement = input('Enter some text: ')

result = entity_recog(statement)

result

q_a = pipeline('question-answering')

result = q_a ({
     'question':'Who is the main character of the story?',
     'context':'''
     The Clockmaker's Secret
In a quiet town nestled between misty hills, lived an old clockmaker named Elias. His tiny shop was filled with clocks of every kind—grandfather clocks that echoed through the night, delicate pocket watches that shimmered in golden cases, and tiny cuckoo clocks with hand-painted birds.

One stormy evening, a young girl named Lila wandered into his shop, soaked and shivering. She held a broken locket watch that had belonged to her mother.

Elias took the watch gently and examined it under his lamp. "This watch doesn’t just keep time," he whispered, "it remembers it."

As he worked, strange things began to happen—the clocks in the shop ticked backward, and the air shimmered like heat on stone. Lila blinked, and suddenly, she was watching a memory unfold in front of her: her mother laughing in the sun, holding the same watch.

When Elias handed it back, the watch glowed warmly. "It’s fixed," he said, "but more importantly, so is the time you thought was lost."

Lila left the shop smiling, the memory cradled in her hand.

Elias turned back to his workbench, the ticking of time carrying on as if it had never stopped.

 '''
})

result

from transformers import pipeline

summarization = pipeline('summarization')

text = input('Enter some text: ')

result = summarization(text,max_length=50)

result

q_a = pipeline('question-answering')

while True:
  res=q_a({
      'question':input('Enter your question: '),
      'context':"""The SmartFit Pro Watch is an advanced wearable device designed to seamlessly blend fitness, health, and lifestyle tracking into one sleek package. Equipped with a high-resolution AMOLED display, it monitors heart rate, sleep patterns, oxygen levels, and daily activity in real time. With built-in GPS, customizable watch faces, and water resistance up to 50 meters, it's perfect for both athletes and everyday users. The long-lasting battery ensures up to 10 days of use on a single charge, making it a reliable companion for any schedule. Whether you're running a marathon or attending a meeting, the SmartFit Pro keeps you connected, informed, and on track.
"""

  })
  print(res['answer'])